apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: will-app
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: confs/
    repoURL: https://github.com/ytaousi/ytaousi_ception.git
    targetRevision: HEAD