---
apiVersion: v1
kind: Service
metadata:
  name: application1
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: application1-port
  selector:
    app:  application1
---
apiVersion: v1
kind: Service
metadata:
  name: application2
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: application2-port
  selector:
    app:  application2
---
apiVersion: v1
kind: Service
metadata:
  name: application3
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: application3-port
  selector:
    app:  application3
---