Vagrant.configure("2") do |config|
    config.vm.box = "generic/rhel8" # redHat / centos / ubuntu / alpine !!??
    
    config.vm.define "ytaousiS" do |master|
        master.vm.hostname = "ytaousiS"
        master.vm.network "private_network", ip: "192.168.56.110"
        master.vm.provider "virtualbox" do |v|
            v.name = "ytaousiS"
            v.customize ["modifyvm", :id, "--memory", "1024"]
            v.customize ["modifyvm", :id, "--cpus", "1"]
            v.customize ["modifyvm", :id, "--name", "ytaousiS"]
        end
        master.vm.provision "shell" do |s|
            s.path = "./initScripts/masterScript.sh"
        end
    end
    config.vm.define "ytaousiSW" do |worker|
        worker.vm.hostname = "ytaousiSW"
        worker.vm.network "private_network", ip: "192.168.56.111"
        worker.vm.provider "virtualbox" do |v|
            v.name = "ytaousiSW"
            v.customize ["modifyvm", :id, "--memory", "1024"]
            v.customize ["modifyvm", :id, "--cpus", "1"]
            v.customize ["modifyvm", :id, "--name", "ytaousiSW"]
        end
        worker.vm.provision "shell" do |s|
            s.path = "./initScripts/workerScript.sh"
        end
    end
end