Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-16.04" # redHat / centos / ubuntu / alpine !!??
    config.vm.synced_folder "." , "/vagrant" , disabled: true
    config.vm.define "ytaousiS" do |master|
        master.vm.hostname = "ytaousiS"
        master.vm.network "private_network", ip: "192.168.56.110"
        master.vm.network "forwarded_port", guest: 6443, host: 6443, host_ip: "0.0.0.0"
        master.vm.synced_folder "./shared", "/vagrantShared"
        master.vm.provider "virtualbox" do |v|
            v.name = "ytaousiS"
            v.customize ["modifyvm", :id, "--memory", "1024"]
            v.customize ["modifyvm", :id, "--cpus", "1"]
            v.customize ["modifyvm", :id, "--name", "ytaousiS"]
        end
        
        master.vm.provision "shell" do |s|
            s.path = "./initScripts/masterScript.sh"
        end
    end
    config.vm.define "ytaousiSW" do |worker|
        worker.vm.hostname = "ytaousiSW"
        worker.vm.network "private_network", ip: "192.168.56.111"
        worker.vm.synced_folder "./shared", "/vagrantShared"
        worker.vm.provider "virtualbox" do |v|
            v.name = "ytaousiSW"
            v.customize ["modifyvm", :id, "--memory", "1024"]
            v.customize ["modifyvm", :id, "--cpus", "1"]
            v.customize ["modifyvm", :id, "--name", "ytaousiSW"]
        end
        worker.vm.provision "shell" do |s|
            s.path = "./initScripts/workerScript.sh"
        end
    end
end