$scriptS = <<-SCRIPT
        apt-get update
        apt-get upgrade -y
        export node_address=$(ip a show eth1 | grep "inet " | awk '{print $2}' | cut -d / -f1)
        export node_interface="eth1"
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip=${node_address} --flannel-iface ${node_interface} --write-kubeconfig-mode 644 server --no-deploy=servicelb --no-deploy=traefik" sh -
        sudo cp /var/lib/rancher/k3s/server/node-token /vagrant/shared
        sudo cp /etc/rancher/k3s/k3s.yaml /vagrant/shared
        sudo sed -i "s|server: https://127.0.0.1:6443|server: https://192.168.56.110:6443/|g" /vagrant/shared/k3s.yaml
        SCRIPT

$scriptSW = <<-SCRIPT
        apt-get update
        apt-get upgrade -y
        export node_address=$(ip a show eth1 | grep "inet " | awk '{print $2}' | cut -d / -f1)
        export node_interface="eth1"
        
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip=${node_address} --flannel-iface ${node_interface}" K3S_TOKEN=$(cat /vagrant/shared/node-token) K3S_URL="https://192.168.56.110:6443"  sh -
        
        sudo mkdir /etc/rancher/k3s
        sudo cp /vagrant/shared/k3s.yaml /etc/rancher/k3s
        export KUBECONFIG=/vagrant/shared/k3s.yaml
        
        SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-16.04" # redHat / centos / ubuntu / alpine !!??

    config.vm.define "ytaousiS" do |master|
        master.vm.hostname = "ytaousiS"
        master.vm.network "private_network", ip: "192.168.56.110"
        master.vm.provider "virtualbox" do |v|
            v.name = "ytaousiS"
            v.customize ["modifyvm", :id, "--memory", "1024"]
            v.customize ["modifyvm", :id, "--cpus", "1"]
            v.customize ["modifyvm", :id, "--name", "ytaousiS"]
        end
        
        master.vm.provision "shell", inline: $scriptS
    end
    config.vm.define "ytaousiSW" do |worker|
        worker.vm.hostname = "ytaousiSW"
        worker.vm.network "private_network", ip: "192.168.56.111"
        worker.vm.provider "virtualbox" do |v|
            v.name = "ytaousiSW"
            v.customize ["modifyvm", :id, "--memory", "1024"]
            v.customize ["modifyvm", :id, "--cpus", "1"]
            v.customize ["modifyvm", :id, "--name", "ytaousiSW"]
        end

        worker.vm.provision "shell", inline: $scriptSW

    end
end