apiVersion: apps/v1
kind: Deployment
metadata:
  name: application1
  # namespace: appsenv
  labels:
    app: application1
spec:
  selector:
    matchLabels:
      app: application1
  replicas: 1
  template:
    metadata:
      labels:
        app: application1
    spec:
      containers:
      - name: application1-container
        image: paulbouwer/hello-kubernetes:1.10
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application2
  # namespace: appsenv
  labels:
    app: application2
spec:
  selector:
    matchLabels:
      app: application2
  replicas: 1
  template:
    metadata:
      labels:
        app: application2
    spec:
      containers:
      - name: application2-container
        image: paulbouwer/hello-kubernetes:1.10
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---