---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  labels:
    name: ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
    paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: application3
            port:
              number: 80
  - http:
    - host: app2.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: application2
              port:
                number: 80
  - http:
    - host: app1.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: application1
              port:
                number: 80
  
---